"""
LangGraph state definitions.
"""

import operator
from typing import Annotated, Any, TypedDict


class AgentState(TypedDict):
    """
    The state shared across all LangGraph nodes.
    """
    workspace_id: str
    user_id: str
    original_query: str
    
    # Generated by Planner
    plan: str
    search_queries: list[str]
    
    # Tool Execution State
    tool_calls: list[dict[str, Any]]
    tool_results: Annotated[list[dict[str, Any]], operator.add]
    
    # Generated by Retriever
    # Using operator.add ensures that if multiple retrieval cycles occur, results are appended
    retrieved_documents: Annotated[list[dict[str, Any]], operator.add]
    
    # Generated by Research/Analysis
    analysis: str
    
    # Generated by Critic
    critic_feedback: str
    is_approved: bool
    
    # Generated by Final Answer
    final_answer: str
    
    # Iteration tracker to prevent infinite loops
    iterations: int
